include: package:lints/recommended.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude: [ build/** ]
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    - always_declare_return_types
    - cancel_subscriptions
    - close_sinks
    - comment_references
    - one_member_abstracts
    - only_throw_errors
    - prefer_single_quotes
    - avoid_shadowing_type_parameters
    - await_only_futures
    - always_put_required_named_parameters_first
    - always_specify_types
    - always_use_package_imports
    - annotate_overrides
    - avoid_annotating_with_dynamic
    - avoid_empty_else
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
    - empty_constructor_bodies
    - empty_statements
    - require_trailing_commas
    - join_return_with_assignment
    - overridden_fields
    - prefer_collection_literals
    - prefer_final_fields
    - prefer_final_locals
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_is_not_operator
    - sized_box_for_whitespace
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_getters_setters
    - unnecessary_lambdas
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_null_checks
    - unnecessary_null_in_if_null_operators
    - unnecessary_nullable_for_final_variable_declarations
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - unnecessary_statements
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - unnecessary_this
    - unrelated_type_equality_checks
    - use_full_hex_values_for_flutter_colors
formatter:
  page_width: 140
  trailing_commas: preserve