include: package:lints/recommended.yaml

analyzer:
  exclude: [ build/**, generated_bindings.dart ]
  language:
    strict-raw-types: true
  strong-mode:
    implicit-casts: false

linter:
  rules:
    - cancel_subscriptions