name: rgb_app
description: RGB is nice
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=3.2.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  bloc_concurrency: 0.3.0
  collection: 1.19.1
  cupertino_icons: 1.0.8
  flutter_bloc: 9.1.0
  flutter_hooks: 0.20.5
  freezed_annotation: 3.0.0
  get_it: 8.0.3
  hydrated_bloc: 10.0.0
  hooked_bloc: 1.6.0
  image: 4.5.3
  json_annotation: 4.9.0
  keyboard_event: 0.3.4
  path: 1.9.1
  path_provider: 2.1.5
  rxdart: 0.28.0
  system_tray: 2.0.3
  vector_math: 2.1.4
  web_socket_channel: 3.0.2
  window_manager: 0.4.3
  windows_single_instance: 1.0.1
  win_ble: 1.1.1
dev_dependencies:
  build_runner: 2.4.15
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  freezed: 3.0.2
  json_serializable: 6.9.4
flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.ico
    - assets/rgbAppService/
    - assets/rgbAppService/runtimes/
    - assets/rgbAppService/runtimes/win/
    - assets/rgbAppService/runtimes/win/lib/
    - assets/rgbAppService/runtimes/win/lib/net7.0/
