name: rgb_app
description: RGB is nice
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  libusb: ^0.3.23+2
  ffigen: ^4.1.3
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  keyboard_event: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
ffigen:
  output: 'generated_bindings.dart'
  headers:
    entry-points:
      - 'libusb.h'
