name: rgb_app
description: RGB is nice
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  libusb: ^0.3.23+2
  ffigen: ^4.1.3
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  keyboard_event: ^0.3.2
  hydrated_bloc: ^9.1.2
  path_provider: ^2.0.10
  get_it: ^7.2.0
  rxdart: ^0.27.7
  image: ^4.0.13
  vector_math: ^2.1.4
  system_tray: ^2.0.3
  path: ^1.8.3
  web_socket_channel: ^2.4.0
  win32: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:
  uses-material-design: true
  assets:
    - assets/libusb-1.0.dll
    - assets/USBHotPlug.dll
    - assets/app_icon.ico
    - assets/rgbAppService/
    - assets/rgbAppService/runtimes/
    - assets/rgbAppService/runtimes/win/
    - assets/rgbAppService/runtimes/win/lib/
    - assets/rgbAppService/runtimes/win/lib/net7.0/
ffigen:
  output: 'generated_bindings.dart'
  headers:
    entry-points:
      #  - 'assets/libusb.h'
      - 'assets/UsbHotPlug.h'
