name: rgb_app
description: RGB is nice
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  libusb: ^0.3.23+2
  ffigen: ^4.1.3
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  keyboard_event: ^0.3.2
  hydrated_bloc: ^8.1.0
  path_provider: ^2.0.10
  get_it: ^7.2.0
  property_change_notifier: ^0.3.0
  rxdart: ^0.27.7
  flutter_colorpicker: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/libusb-1.0.dll
    - assets/USBHotPlug.dll
ffigen:
  output: 'generated_bindings.dart'
  headers:
    entry-points:
    #  - 'assets/libusb.h'
      - 'assets/UsbHotPlug.h'
