name: rgb_app
description: RGB is nice
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  collection: ^1.18.0
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  ffi: ^1.2.1
  ffigen: ^6.0.0
  flutter_bloc: ^8.1.4
  flutter_hooks: ^0.20.5
  get_it: ^7.6.7
  hydrated_bloc: ^9.1.4
  image: ^4.1.7
  keyboard_event: ^0.3.4
  libusb: ^0.3.23+2
  path: ^1.9.0
  path_provider: ^2.0.15
  rxdart: ^0.27.7
  system_tray: ^2.0.3
  vector_math: ^2.1.4
  web_socket_channel: ^2.4.4
  win32: ^2.6.1
  window_manager: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:
  uses-material-design: true
  assets:
    - assets/libusb-1.0.dll
    - assets/app_icon.ico
    - assets/rgbAppService/
    - assets/rgbAppService/runtimes/
    - assets/rgbAppService/runtimes/win/
    - assets/rgbAppService/runtimes/win/lib/
    - assets/rgbAppService/runtimes/win/lib/net7.0/
ffigen:
  output: 'generated_bindings.dart'
