name: rgb_app
description: RGB is nice
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=3.2.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  bloc_concurrency: 0.2.4
  collection: 1.18.0
  cupertino_icons: 1.0.6
  flutter_bloc: 8.1.4
  flutter_hooks: 0.20.5
  freezed_annotation: 2.4.1
  get_it: 7.6.7
  hydrated_bloc: 9.1.4
  image: 4.1.7
  json_annotation: 4.8.1
  keyboard_event: 0.3.4
  path: 1.9.0
  path_provider: 2.0.15
  rxdart: 0.28.0
  system_tray: 2.0.3
  vector_math: 2.1.4
  web_socket_channel: 3.0.1
  window_manager: 0.4.2
  windows_single_instance: 1.0.1
dev_dependencies:
  build_runner: 2.4.13
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0
  freezed: 2.4.7
  json_serializable: 6.7.1
flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.ico
    - assets/rgbAppService/
    - assets/rgbAppService/runtimes/
    - assets/rgbAppService/runtimes/win/
    - assets/rgbAppService/runtimes/win/lib/
    - assets/rgbAppService/runtimes/win/lib/net7.0/
